### PR TITLE
Feature/update endpoint

### PR DESCRIPTION
**Pull request by pm3310**

### CODE REVIEW

**Comment by pm3310** [comment]
@ilazakis I followed the docs from SageMaker that the SageMaker library will raise a ValueError if the endpoint doesn't exist already. I'll add one small white test for that ;-)

**Comment by ilazakis** [comment]
Thanks @pm3310 , if it results in excessive / painful mocking and we can skip, up to you 👍

**Comment by pm3310** [comment]
@ilazakis  I just tried to do it but it results in a very unreadable test :-(

**Comment by ilazakis** [comment]
Addresses #95

**Pull request merged**
